service: demo-donetcore
app: demo-ws1508
tenant: triminh1992

provider:
  name: aws
  runtime: dotnetcore2.1
  VERSION_DYNAMODB_TABLE: "Version"

# you can overwrite defaults here
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
       - "s3:CreateBucket"
     Resource: "*"
   - Effect: "Allow"
     Action:
       - dynamodb:DescribeTable
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
       - dynamodb:GetRecords
       - dynamodb:GetShardIterator
       - dynamodb:DescribeStream
       - dynamodb:ListStreams
     Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  artifact: bin/release/netcoreapp2.1/deployment.zip

functions:
  process:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Process
    events:
      - http:
          path: process/
          method: get
  get-version:
    handler: CsharpHandlers::AWSVersion.Version::GetVersion
    events:
      - http:
          path: version/
          method: get

  update-version:
    handler: CsharpHandlers::AWSVersion.Version::UpdateVersion
    events:
      - http:
          path: version/
          method: put
  notify:
    handler: CsharpHandlers::AWSVersion.Version::NotifyStream
  ws-connect:
    handler: CsharpHandlers::DemoWebsocket.AWSWebsocket::Subcribe
    events:
      - websocket:
          route: $connect
  ws-disconnect:
    handler: CsharpHandlers::DemoWebsocket.AWSWebsocket::Disconnect
    events:
      - websocket:
          route: $disconnect
  broadcast:
     handler: CsharpHandlers::DemoWebsocket.AWSWebsocket::Broadcast
     events:
      - websocket:
          route: broadcast
  stream-handling:
    handler: CsharpHandlers::DemoWebsocket.AWSWebsocket::StreamReceiver
resources:
  Resources:
    Version:
       Type: 'AWS::DynamoDB::Table'
       DeletionPolicy: Retain
       Properties:
         AttributeDefinitions:
           - AttributeName: id
             AttributeType: N
         KeySchema:
           - AttributeName: id
             KeyType: HASH
         ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
         TableName: "Version"
    WSConnectionTable:
       Type: 'AWS::DynamoDB::Table'
       DeletionPolicy: Retain
       Properties:
         AttributeDefinitions:
           - AttributeName: connectionId
             AttributeType: S
         KeySchema:
           - AttributeName: connectionId
             KeyType: HASH
         ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
         TableName: "WSConnection"